import express from 'express';
import { findAllSettingsControllers, findSettingsByUserIdControllers, insertSettingsControllers, updateSettingsControllers,deleteSettingsControllers } from "../controllers/settingsController.js";
import { verifyToken } from "../middleware/authMiddleware.js";
import { authorizeRoles } from '../middleware/authorizeRoles.js';
const router = express.Router();
router.get("/", verifyToken, authorizeRoles("admin"), findAllSettingsControllers);
router.get("/users/:id", verifyToken, authorizeRoles("admin"), findSettingsByUserIdControllers);
router.post("/",verifyToken, authorizeRoles("admin"), insertSettingsControllers);
router.patch("/users/:id", verifyToken, authorizeRoles("admin"), updateSettingsControllers);
router.delete("/users/:id", verifyToken, authorizeRoles("admin"), deleteSettingsControllers);
export default router;
